# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/shiba/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),shiba)

$(call add-radio-file-sha1-checked,radio/abl.img,3140b3d37b11f8bd87c8f3454cc4eb7d1aa43de4)
$(call add-radio-file-sha1-checked,radio/bl1.img,18567e50e19400bf7a53f12a74b02f4d8ae32f1a)
$(call add-radio-file-sha1-checked,radio/bl2.img,85df1717c54253cb7f0b072a9225521d227875d1)
$(call add-radio-file-sha1-checked,radio/bl31.img,33efba9866145f719b10b2f8983ebd5028680892)
$(call add-radio-file-sha1-checked,radio/gcf.img,0b1c1e670f8e640c90817568d4927430941d468e)
$(call add-radio-file-sha1-checked,radio/gsa.img,4991ffb969b995ad0e1d0cf1e4420fa9ab7efcd6)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,0094914e0cf22bda6c7bd0b777cb82a7fd78ab01)
$(call add-radio-file-sha1-checked,radio/ldfw.img,a97147749717e191800fae82476700b6f8a00293)
$(call add-radio-file-sha1-checked,radio/modem.img,10cb0a7bff0f1abd4f822048ebe60cc763dc8be1)
$(call add-radio-file-sha1-checked,radio/pbl.img,46f70584b448905a2f3425b6d97f245a4581ea9d)
$(call add-radio-file-sha1-checked,radio/tzsw.img,4a37fb9eda37982332a146e6c2e7cc698d1955fe)

endif
