# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/shiba/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),shiba)

$(call add-radio-file-sha1-checked,radio/abl.img,19ed80b5f5d3907bdcbd7dbde7f49dac7615cbcc)
$(call add-radio-file-sha1-checked,radio/bl1.img,43beed8ccfa79b7d0812a318828cc0cdbe2772ab)
$(call add-radio-file-sha1-checked,radio/bl2.img,fa9a4e037918870c20246112c791ef1eaf7522c7)
$(call add-radio-file-sha1-checked,radio/bl31.img,c9a9baeca502cc2971a485f6c350333f33d33d0d)
$(call add-radio-file-sha1-checked,radio/gcf.img,93bc29d26c680bba9b40309d916e267e07f312c2)
$(call add-radio-file-sha1-checked,radio/gsa.img,34ad903ce59ecbf4de722cacf94fd6661b250da4)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,f58f41a91a300c47ac0eafe3a8cd8dd37b1ea7b3)
$(call add-radio-file-sha1-checked,radio/ldfw.img,ad39f170b9656a710f3b11275612fd0ba97a76ef)
$(call add-radio-file-sha1-checked,radio/modem.img,10cb0a7bff0f1abd4f822048ebe60cc763dc8be1)
$(call add-radio-file-sha1-checked,radio/pbl.img,d1e28481f4fbe88fa17edf076145b62f203874be)
$(call add-radio-file-sha1-checked,radio/tzsw.img,6433a91712b6102f86a3805d8135227099737d1f)

endif
